spring.application.name=account-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/di2win_bank
spring.datasource.username=di2win
spring.datasource.password=di2win123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
